select * from customer 
limit 10


-- Q1: Total revenue generated by male vs female customers

SELECT gender ,SUM(purchase_amount) AS Revenue
FROM customer
GROUP BY gender
ORDER BY Revenue DESC;

-- Q2: which customer used discount still spend more than average purchase amount.

SELECT customer_id ,purchase_amount
FROM customer WHERE discount_applied='Yes'
AND purchase_amount>=(
SELECT ROUND(AVG(purchase_amount),0)as average_amount
FROM customer)
ORDER BY purchase_amount DESC,customer_id ;


-- Q3: top 5 products with highest average rating
SELECT item_purchased, ROUND(AVG(review_rating :: NUMERIC),2) AS "Average_rating"
FROM customer
group by item_purchased
ORDER BY AVG(review_rating) DESC
LIMIT 5;


-- Q4: compare the average purchase amount between standard and express shipping.
select shipping_type, ROUND(AVG(purchase_amount :: NUMERIC),2)as Average_amount from customer
WHERE shipping_type IN ('Standard','Express')
GROUP BY shipping_type;


-- Q5: Do subscribed customers spend more? compare average spend and total revenue between subscribers and non subscribers

SELECT subscription_status,ROUND(AVG(purchase_amount),2) AS "average_spend",
		SUM(purchase_amount) AS "Total Revenue",
		COUNT(*) AS "Total Orders"
FROM customer
GROUP BY subscription_status;

-- Q6: which 5 products have the highest percentage of purchases with discount applied.

SELECT item_purchased,
	ROUND(100*SUM(CASE WHEN discount_applied='Yes' THEN 1 ELSE 0 END)/COUNT(*),2) AS discount_rate
	
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

-- Q7: segment customers into new,returning and loyal based on their total number of previous purchases and show count of each segment.


WITH customer_type AS(
	SELECT customer_id,previous_purchases,
	CASE 
		WHEN previous_purchases=1 THEN 'New'
		WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
		ELSE 'Loyal'
		END AS customer_segment
	FROM customer
)
SELECT customer_segment,COUNT(*)AS "No of customers"
FROM customer_type
GROUP BY customer_segment;

-- Q8: what are the top 3 most purchased products in each category


WITH top3products AS(

SELECT category,item_purchased,
		COUNT(customer_id)as total_orders,
		RANK()OVER(PARTITION BY category ORDER BY COUNT(customer_id) DESC)as item_rank
FROM customer
GROUP BY category,item_purchased

)

SELECT item_rank,category,item_purchased,total_orders
from top3products
where item_rank<=3;


-- Q9: Are customers who are repeat buyers (more than 5 purchases) also likely to subscribe?


select subscription_status,
		COUNT(customer_id) AS repeat_buyers

FROM customer
WHERE previous_purchases>5
GROUP BY subscription_status


-- Q10 : what is the revenue contribution for each age group?
select age_group,
		SUM(purchase_amount) AS revenue
from customer
group by age_group
order by revenue desc


select * from customer